[rtpengine]
interface = internal/{{RTPENGINE_INTERFACE_INTERNAL_BIND_IP}};external/{{RTPENGINE_INTERFACE_EXTERNAL_BIND_IP}}!{{RTPENGINE_INTERFACE_EXTERNAL_ADVERTISE_IP}}
listen-ng = {{RTPENGINE_LISTEN_NG_IP}}:2223
listen-cli = {{RTPENGINE_LISTEN_CLI_IP}}:9900
log-level = {{RTPENGINE_LOG_LEVEL}}
log-level-subsystem = {{RTPENGINE_LOG_LEVEL_SUBSYSTEM}}
log-stderr = true
foreground = true
port-min = {{RTPENGINE_RTP_PORT_START}}
port-max = {{RTPENGINE_RTP_PORT_END}}
delete-delay = 0
timeout = 60
offer-timeout = 15
final-timeout = 0
