applications/mod_acl
applications/mod_commands
applications/mod_dptools
dialplans/mod_dialplan_xml
endpoints/mod_sofia
event_handlers/mod_event_socket
formats/mod_native_file
formats/mod_sndfile
loggers/mod_console
loggers/mod_logfile
asr_tts/mod_flite
asr_tts/mod_piper_tts
codecs/mod_opus
